### PR TITLE
Replace the 2017a string definition by the 2016b one

### PR DESCRIPTION
**Pull request by acfloria**
Use string('text') instead of "text".

@ASM3 please check if it runs now for you and if not please post the error message.

### CODE REVIEW

**Comment by ASM3** [comment]
Still has "string" related issues. This time it is the "exist" function (this is where I stopped in the last try)

**Error details:**
Undefined function 'exist' for input arguments of type 'string'.

Error in logconv/ImportPX4LogData (line 384)
        if exist(csv_file, 'file') == 2

Error in logconv (line 103)
    ImportPX4LogData();

**Comment by acfloria** [comment]
@ASM3 I can you test it again.

**Comment by ASM3** [comment]
Pushed some small fixes, it work on my machine now. Nevertheless the conversion is very slow.

**Comment by ASM3** [comment]
I restarted the computer and it helped a bit... nevertheless, here are the timer values (file size 25MB):
INFO: Start importing the log data.
INFO: Converting the ulog file to csv took 43.1684 s.
INFO: Starting to import the csv data into matlab.
INFO: Importing the csv data to matlab took 181.4073 s.
INFO: Finished importing the log data.
INFO: Not cropping the logging data.

**Comment by acfloria** [comment]
Importing the csv data took the same amount of time for me. However the ulog to csv conversion was done on linux within 10 seconds. When I test it on windows the ulog conversion also takes around 40 seconds.

**Pull request merged**
